spring:
  profiles:
    active: local #local,dev,real → 운영환경 지정
    
  #JSP 호출 시 view 설정
  mvc:
    view: #view 경로 및 확장자 지정
      prefix: /WEB-INF/views/
      suffix: .jsp
    
  datasource: #DB접속 설정
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:3306:xe
    username: c##user002
    password: 1234
    hikari:
      connection-timeout: 30000 #클라이언트가 pool에 connection을 요청하는데 기다리는 최대시간 설정(30)
      maximum-pool-size: 10 #최대 connection 개수 설정
      max-lifetime: 180000 #connection pool에서 살아있을 수 있는 커넥션의 최대 수행 시간 1,800초(30분)

  messages: #메시지 설정
    basename: messages.validation
    encoding: UTF-8
    
  #JSP/클래스 변경 시 바로 갱신되게끔    
  devtools: #View reload
    livereload:
      enabled: true
    restart: #controller, model단이 바뀌었을 때 프로젝트 재시작 설정(Classpath에 있는 모든 파일)
      enabled: true
 
  servlet:
    multipart:
      max-file-size: 700MB #파일 1개당 최대 사이즈
      max-request-size: 1000MB #요청당 최대 파일 크기
      
mybatis: #mybatis 설정
  type-aliases-package: kr.spring.**.vo #하위 경로 -> **
  mapper-locations: kr/spring/**/dao/*.xml
  
logging: #Log 지정
  level:
    '[kr.spring]': debug #kr.spring 하위는 모두 debug 모드로 지정
    
#서버 포트 설정, 인코딩 처리    
server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true #http 인코딩 지원 활성화 여부 (charset의 option)
      force: true #charset의 option